### ISSUE TITLE
Unprintable entries in PS1 in iTerm2

### ISSUE THREAD

**Issue by Dmitry-Kucher** [horrower/osx-terminal-powershell#2]
According to https://github.com/horrower/osx-terminal-powershell/blob/master/powerfull.bash#L94
PS1 contains unprintable symbols it's causes some problems. See screenshot:

<img width="430" alt="screen shot 2018-02-14 at 12 06 22" src="https://user-images.githubusercontent.com/2552032/36195726-7f00b672-117f-11e8-86b6-a21b546a1ac2.png">

**Comment by horrower** [comment]
Did you install powershell font in your OSX? And did you choose it as default in your Terminal or iTerm ?

**Comment by Dmitry-Kucher** [comment]
My bad. 

<img width="327" alt="screen shot 2018-02-14 at 12 34 40" src="https://user-images.githubusercontent.com/2552032/36196973-73b44d02-1183-11e8-9b64-4ecc7f8c4064.png">

To enable font in `iTerm2` both options **Font** and **Non-ASCII Font** should pointed to powerline font

**Comment by horrower** [comment]
There is a bug with iTerm 2
1) Setup font
2) Click Use different font fot non-ASCII text
(Non-ACSII font options SHOULD be visible but its not)
3) Save and close setting
4) Go to settings again, now you should see NON-ASCII FONT options with default font "Monaco"
5) Change font to powershell and save settings
